### PR TITLE
Using maildev as a middleware

### PR DESCRIPTION
**Pull request by ebourmalo**
This PR enable using Maildev as a middleware of an existing app.

The README explains how it's achieved:
```
We can use maildev within an existing app by giving an additional parameter
`middleware` to the options object. We use a proxy to redirect all maildev requests
to the maildev app.
```

Everything works fine when no middleware option is passed.

Feedbacks are welcome :)

### CODE REVIEW

**Comment by ghislainf** [comment]
:+1:

**Comment by djfarrelly** [comment]
Wow, this is pretty cool @ebourmalo! I love this :+1: - I'm going to test this out and perhaps change the `middleware` variable to something like `baseUrl` or `basePathname`, but otherwise from a quick review this looks like an awesome addition to the project :smile: 

Thanks so much for your contribution!

PS - If you have a minute, I'd love to hear how you're using MailDev, specifically in the situation of the proxy. I always like to learn more about how people are using it!

**Comment by ebourmalo** [comment]
I'll make an update for the option to become `baseUrl`, `middleware` is not very speaking :)

About our usage, we have a back-office (sending emails, triggering jobs, ..) and we wanted to have all external dashboards (emails, job schedules) within this app, connected as express subapps (middlewares).

So to make things simple, we have:
- our back-office at `localhost:3000/`
- our task scheduler dashboard at `localhost:3000/agenda`
- our email dashboard (maildev) at `localhost:3000/maildev`

And because we wrap all of that into a docker image, we can finally expose only one port.
So even if there are multi apps running on the instance, we can reach only 1 port. 
So the entry point is the back-office app, and we use proxy to connect the subapps and reach them via simple routes :)

**Comment by firminzoc** [comment]
:+1:

**Comment by ebourmalo** [comment]
Thanks for creating and maintaining this module @djfarrelly, this is really awesome and handful :)

Let me know if you need any help, update or so!

**Comment by djfarrelly** [comment]
Hi @ebourmalo, I'm working on getting this 0.13 release out w/ your changes and I'm wondering if you've tested attachments and inline image attachments w/ the proxy yet. I just want to make sure that has been tested before this goes out! Thanks :)

**Comment by ebourmalo** [comment]
Awesome @djfarrelly, I'm making some right now tests and I'll get back asap :)

**Comment by djfarrelly** [comment]
@ebourmalo, I started writing some tests, I may be super close to finishing them up!

**Pull request merged**
