### PR TITLE
Connection close and relay

### PR DESCRIPTION
**Pull request by donut87**
Hi,

these two commits allow us to relay incoming mails. diresis commit ensures, that there is no "null" recipient or sender and the other commit closes the smtp connection after sending an email. This was necessary because we always got an error when the connection was closed by the smtp server.

Cheers

Christian

### CODE REVIEW

**Comment by diresi** [comment]
Works for me, thanks a lot!

**Comment by djfarrelly** [comment]
So sorry about the delay on this one @donut87 and @diresi! I really appreciate this awesome fix and will be pushing out 0.12.1 to npm ASAP :+1:

**Comment by djfarrelly** [comment]
Hi @donut87! I've pulled this down and have done a bunch of testing and when using Gmail, this will work on the first relay, but will fail on any any future relays. It seems the reconnection needed to be changed to `config.pass && config.user`.

I'm curious - why did you choose to instantiate a new SMTPConnection object in `resetRelayConfiguration` instead of letting it quit then reconnect with client.connect? I'm running into more issues when combined with the changes in #85 - Thanks for your help!

**Comment by diresi** [comment]
@djfarrelly I've started this in #86, maybe the description there helps?

**Comment by djfarrelly** [comment]
Ah ok, thanks @diresi - With the timeout issue I'm thinking a better flow for maildev might be `create client > connect > login > send > quit` vs. `connect > login > send > quit > create client`. Long term there could be a way to test if the connection was still active vs. quitting + re-connecting :) Thanks for your help!

**Pull request merged**
