### PR TITLE
added unread items count in the <title>

### PR DESCRIPTION
**Pull request by AlexDpy**
First, thank you for this really nice package !

I just added the count of unread items in the title, so now we can see, f.e., (5) MailDev.

### CODE REVIEW

**Comment by ProPheT777** [comment]
:+1:

**Comment by djfarrelly** [comment]
Thanks for this @AlexDpy! Looks good to me, I'll make sure to test and merge it as soon as soon as I can :+1:

**Comment by djfarrelly** [comment]
Hey @AlexDpy! I pulled this down and tested the code out and there are a couple bugs with the current implementation. Using `$scope.unreadItems--;` in the `$scope.markRead` method can actually make the unread count become negative. If a user clicks an already read email, it will decrease the unread count regardless of if it's already been read. 

One thought I had was to recalculate the absolute value each time instead of incrementing/decrementing a counter. I was thinking a function like this:
```javascript
var countUnread = function() {
  $scope.unreadItems = $scope.items.filter(function(email) {
    return !email.read;
  }).length;
};
```
And called that every time we received new mail/read an email! What do you think?

**Comment by AlexDpy** [comment]
You're right. I've updated the PR. I'm just not sure about the usage of the $promise in the loadData(), but it works.
```js
var loadData = function() {
$scope.items = Email.query();
+ $scope.items.$promise.then(function() {
+ countUnread();
+ });
};
```

**Comment by djfarrelly** [comment]
:+1: Thanks @AlexDpy, I'll get this out in `0.9.1`

**Pull request merged**
