### PR TITLE
Replace simplesmtp with smtp-server and smtp-connection djfarrelly/MailDev#30

### PR DESCRIPTION
**Pull request by Seidr**
RE djfarrelly/MailDev#30

I've tested receiving emails with and without attachments, as well as relaying with and without authentication. All appears to work, however I'm not sure about the definitions of the callbacks in lib/mailserver.js around lines 417-466 (in particular mailConnectCallback and mailSendCallback). Open to suggestions as to how it can be improved - it just feels messy scoping them like that.

The change to smtp-server and smtp-connection does require NodeJS 0.12, as it depends upon Sets, which became available with 0.12.

### CODE REVIEW

**Comment by Seidr** [comment]
Also, not sure about the level of verbosity at the moment. This could likely be reduced, and messages piped to logger.

**Comment by Seidr** [comment]
Ah, of course, I'll take a look at the tests during my break. *facepalm*

**Comment by Seidr** [comment]
Whoops - fixed the broken tests. The wrong method was being called in the end API.

**Comment by Seidr** [comment]
Ok, I've fixed the broken 0.12 test, however the 0.10 test is failing due to not having the Set class available to it (as I said, introduced in 0.12). Not sure how to get this green again. Is that a project setting in github that you need to change?

**Comment by Seidr** [comment]
I tried working around this by using the simplesets module, but that just resulting in further (and scarier) errors being thrown. Do we really need to bend over backwards to continue support of 0.10? Not sure of the market share vs 0.12.

**Comment by djfarrelly** [comment]
Hey @Seidr, this was awesome to wake up to! I have a day of work ahead of me, but really want to dig into these changes this weekend, this looks great from a quick look.

It's my gut that market share of 0.10.x is still larger than 0.12.x, but potentially, MailDev could stop supporting Node 0.10.x with MailDev 0.11.0 and for Node 0.10 support a user can continue to use MailDev 0.10.x, I could maintain a branch for any breaking issue and publish patch releases if needed. With the impending Node/io.js merger, I would definitely like to test this on the latest io.js as I think that might hold more weight than Node 0.12 long term (just a personal opinion).

**Comment by djfarrelly** [comment]
hey @Seidr! Man, I'm so sorry that this has sat on the shelf for all this time. The day job and vacation have taken priority recently. One fresh thought I had on this is to be backwards compatible requiring both packages and forking depending on which version of node the user is using. It would be more code and might be messy, but it would ensure it works for everyone no matter what version of Node they're developing. Then the 0.10.x code can be ripped out in the future when it's used less. I'm not really sure how other Node projects handle an issue like this, but I'm open to ideas!

I'm looking through your code right now and going to check more into how this could work.

**Comment by djfarrelly** [comment]
Hey @Seidr, I did the fork I mentioned and added PR #77, what do you think? :)

**Comment by Seidr** [comment]
Good idea re legacy support. Had a look at the PR and it's about as clean as it's going to get while retaining support for node 0.10.x.

Also, don't worry about delays - I know full well how 'real life' can take over from time to time :)

**Comment by djfarrelly** [comment]
Yeah, I had thought about a further abstraction out of mailserver.js, but I think this is ok for now. It's not the cleanest code, but I'm thinking most consumers of the projects won't be digging into the codebase too often :)

**Comment by djfarrelly** [comment]
Thanks again @Seidr! Merged this in, planning to release 0.11.0 today :+1:

**Pull request merged**
