### PR TITLE
set basePathname from command line

### PR DESCRIPTION
**Pull request by diresi**
this is useful when running behind some path-based reverse proxy.

### CODE REVIEW

**Comment by diresi** [comment]
Hmm. I think that travis failed randomly, but how do I repeat the build?

**Comment by mykelyk** [comment]
Can you to close and reopen the PR maybe? I would appreciate if we can merge this as this would make the docker image usable behind a reverse proxy.

**Comment by diresi** [comment]
Done, this time it worked. Btw, docker containers behind an nginx reverse proxy is my exact use case ;).

**Comment by djfarrelly** [comment]
This is great, will merge this in and hopefully release `0.13.4` this afternoon. Thanks @diresi!

**Pull request merged**
