### PR TITLE
check if files in temp folder exist

### PR DESCRIPTION
**Pull request by dszymczuk**

### CODE REVIEW

**Comment by donut87** [comment]
Is there any specific reason to do so? Could you describe the reason for your change?

**Comment by dszymczuk** [comment]
Yes.

I use your mail server in E2E tests. Before each test I use your API to get and delete all mails. And that's point where your app sometimes crashed.
It try to delete mails but it can't because folder / files don't exist.

It could be tricky to reproduce, but you can try send mail and delete all mails 5-10 times in loop.
Maybe you catch error.

**Comment by dszymczuk** [comment]
Any way, this protects your app ;)

**Comment by oktapodia** [comment]
Thanks for your work! Sorry I did not spot your PR earlier, this has already been fixed via the [rimraf](https://www.npmjs.com/package/rimraf) package

**Pull request closed without merging**
